Palindrome checker responsive
SandeepKrSuman/project-gallery pull request #70
Opened 2022-10-25 19:56 UTC by LucianeFernandesRoque

2022-10-26 07:27 UTC, SandeepKrSuman requested changes

2022-10-26 07:27 UTC, SandeepKrSuman commented on public/Projects/VaibhavPalindromeCheck/index.html
> -    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
I guess keeping this bootstrap style was a good idea. 
The previous navbar and button style was looking better.
However if you can make them look better without bootstrap using CSS only then that will be nice as well. Keeping this upto you!

2022-10-26 07:28 UTC, SandeepKrSuman commented
![Screenshot (671)](https://user-images.githubusercontent.com/54541515/197961992-b8a7d163-162e-488c-824d-1717a4a68e14.png)

This definitely does not look good on larger screens. The previous one was better.

2022-10-26 07:29 UTC, SandeepKrSuman commented
Also for mobile-view more can be done.
![Screenshot (672)](https://user-images.githubusercontent.com/54541515/197962305-ad5ca514-7f7c-4fdd-861e-4f42ad6bad74.png)

2022-10-28 07:45 UTC, SandeepKrSuman approved these changes
Looks better than previous version 👍

2022-10-28 19:55 UTC, LucianeFernandesRoque commented
> Looks better than previous version +1
You can do review of the my PR.
If you  have questions or change the code. Thank you for your time and tips

2022-10-29 06:19 UTC, SandeepKrSuman approved these changes

2022-10-29 06:22 UTC, merged